### ISSUE TITLE
Wrong git link

### ISSUE THREAD

**Issue by Creepybits** [NakamuraShippo/ComfyUI-NS-PromptList#3]
In the description both here and on https://comfy.icu/extension/NakamuraShippo__ComfyUI-PromptList

the git link you have provided is: git clone https://github.com/yourusername/ComfyUI-PromptList.git

It should be: git clone https://github.com/NakamuraShippo/ComfyUI-PromptList.git

**Comment by Creepybits** [comment]
I also get this error when I restarted Comfy:

`[ERROR] An error occurred while retrieving information for the 'ComfyUI-PromptList' node.
Traceback (most recent call last):
  File "C:\AI Stuff\ComfyUI\ComfyUI\server.py", line 447, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\AI Stuff\ComfyUI\ComfyUI\server.py", line 424, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI Stuff\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PromptList\ComfyUI_PromptList.py", line 32, in INPUT_TYPES
    "selection": (cls.get_prompt_list(),),
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI Stuff\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PromptList\ComfyUI_PromptList.py", line 56, in get_prompt_list
    instance = cls()
               ^^^^^
  File "C:\AI Stuff\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PromptList\ComfyUI_PromptList.py", line 26, in __init__
    self.data = self.load_yaml()
                ^^^^^^^^^^^^^^^^
  File "C:\AI Stuff\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PromptList\ComfyUI_PromptList.py", line 47, in load_yaml
    return yaml.load(file, Loader=OrderedLoader) or OrderedDict()`

**Comment by Creepybits** [comment]
Hi, sorry for late response. I've gotten the node to work now but I have a question. Is it possible to make it so that you can choose a yalm file? Right now it will only pick up the specific file that's named "Prompts.yalm". It would be nice if you could have several yalm files named for example "animals.yalm, people.yalm, architecture.yalm" etc, and be able to pick anyone of them.

**Comment by Creepybits** [comment]
> > Hi, sorry for late response. I've gotten the node to work now but I have a question. Is it possible to make it so that you can choose a yalm file? Right now it will only pick up the specific file that's named "Prompts.yalm". It would be nice if you could have several yalm files named for example "animals.yalm, people.yalm, architecture.yalm" etc, and be able to pick anyone of them.
> 
> Hi there, thank you so much for the great idea!
> 
> I'm not entirely sure if it’ll work, but it seems like it might be necessary to refresh ComfyUI each time a YAML file is selected. To create a dynamic node that immediately loads the content of another YAML file when one is selected, we'd likely need to modify ComfyUI itself. So, if it works, the process might be something like: selecting the YAML -> refreshing -> loading the YAML.
> 
> I can’t promise to try it out immediately due to work commitments, but I’ll give it a shot when I can.

I totally understand. I don't know how to build nodes myself, so I'm grateful for everyone who shares their work :)
